@startuml

<style>
activityDiagram {
    BackgroundColor #F0E8F5
    BorderColor #FFC0CB
    FontColor #333
    FontName Comic Sans MS
}

diamond {
    BackgroundColor #FFDEE3
    LineColor #FF69B4
    FontColor #FF1493
    FontName Comic Sans MS
    FontSize 16
}

arrow {
    FontColor #FFD700
    FontName Comic Sans MS
    FontSize 16
}

partition {
    LineColor #FF4500
    FontColor #FF6347
    RoundCorner 20
    BackgroundColor #FFE4E1
}

note {
    FontColor #0000FF
    LineColor #8A2BE2
    BackgroundColor #E6E6FA
}

document {
    BackgroundColor #F5F5DC
}

group {
    FontColor #FF69B4
    LineColor #DDA0DD
    BackgroundColor #FFB6C1
}
</style>
title Queue.Add()方法的实现

skinparam ConditionEndStyle diamond
start
group Add()
if (如果queue正在被关闭\n\tq.shuttingDown) then (是)
 :则返回return;
 kill
else(否)
    if (如果该元素已经存在于dirty集合中\n\t\t\tq.dirty.has(item)) then(是)
    :则返回return;
    kill
    else(否)
        :添加到dirty set中\nq.dirty.insert(item);
        if (q.processing.has(item)\n\t    如果正在处理)then(是)
            :则返回return;
            kill
        else(否)
            :则添加到q.queue中; \n q.queue.Push(item);
            :通知getter有新的元素到来 \n\t   q.cond.Signal();
        endif
    endif
endif
end group
stop

@enduml