apiVersion: apps.hyj.cn/v1
kind: Application
metadata:
  name: application-sample
  namespace: default
  labels:
    app: nginx
#    app.kubernetes.io/name: application-operator
#    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
