apiVersion: apps.hyj.cn/v2
kind: Application
metadata:
  name: nginx-sample1
  namespace: default
#  labels:
#    app: nginx
spec:
  workflow:
    replicas: 11
    selector:
      matchLabels:
        app: nginx
    template:
      metadata:
      #        labels:
      #          app: nginx
      spec:
        containers:
          - name: nginx
            image: nginx:1.14.2
            ports:
              - containerPort: 80
  service:
    type: NodePort
    ports:
      - port: 80
        targetPort: 80
        nodePort: 30082
